### PR TITLE
added buffer to concatenate

### PR DESCRIPTION
**Pull request by fabiogermann**
instead of string concatenation (string concatenation will allocate new
memory for every change of the string and sometimes cause a memory
overflow).

### CODE REVIEW

**Comment by inorganik** [comment]
Hi, thanks for contributing! I would like to merge, however it looks like you didn't test your code. When you don't pass an argument to `join()`, it separates with a comma. So you need to change it to an empty string: `join('')`. But that's not all. It's also ignoring nested objects. 

If you can fix these things and thoroughly test before you commit, I can merge.

Thanks,
Jamie

**Comment by fabiogermann** [comment]
sure. i'll have time this weekend

**Comment by fabiogermann** [comment]
I pushed an updated version. the previous errors have been corrected.
However I thought about adding a "newline" in case of nested arrays after the child array was closed.
in your original code that would be line 225

**Comment by inorganik** [comment]
sorry, let this one sit too long and it got outdated.

**Pull request closed without merging**
